### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by Sensest** [rwdkor/RhythmSharp#2]
And here I was thinking your last project was great, holy fuck you outdid yourself with this one!

With that out of the way, there's a lot of things missing for english, the main thing I noticed was the right-click menus from the tabs: General - Tasks - Scheduler.

I can't praise you enough for this project, good luck man, I'll probably consider supporting in your ko-fi.

**Comment by rwdkor** [comment]
Added translations for right-click menus. If you find more missings, please tell me 🌺
