### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by Meister69** [rwdkor/RhythmSharp#3]
Hard to explain this issue but basically, your input in the Tasks menu (See image) doesn't come as the same in-game.
As for the example " keys=4 " the bot will write " keys¿4 " instead, and then will just keep deleting and writing the same message (keys¿4) until you turn off the Tasks.
My guess is that it's related to the keyboard layout or language that it's trying to use. Please let me know if this is a problem in my end.
![RhythmSharp_LN4Hq7JmuA](https://user-images.githubusercontent.com/54419689/90402571-a5722600-e06d-11ea-87d0-64c8938dc594.png)

**Comment by Meister69** [comment]
Oh, and I just updated and noticed that this menu has a translation missing
![RhythmSharp_djWfeurgxk](https://user-images.githubusercontent.com/54419689/90403307-c9823700-e06e-11ea-9365-cbe5e46a4997.png)
Edit: Found another one
![RhythmSharp_ZNq1lpnlkC](https://user-images.githubusercontent.com/54419689/90403554-2847b080-e06f-11ea-974e-e1ec41e3996d.png)

**Comment by rwdkor** [comment]
i'm going to look at this issue. Typing "keys=4" is simulated by 'Class DD Library'. I'm not author of ClassDD, so I will fix with alternative solution.
Thanks for telling me about the problem

Fixed now : https://github.com/rwdkor/RhythmSharp/issues/3#issuecomment-674892924

**Comment by rwdkor** [comment]
https://github.com/rwdkor/RhythmSharp/releases/tag/2020-08-17_3
